#!/usr/bin/env ruby

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

unshift_path = ->(path) {
  p = File.expand_path("../../#{path}", __FILE__)
  $LOAD_PATH.unshift(p) unless $LOAD_PATH.include?(p)
}
unshift_path.call('lib')

require 'bundler/setup'
require 'testing_agent'

exit(TestingAgent::ErrorHandler.call do
  TestingAgent::EntryPoint.call(ARGV.dup)
end)
